version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: sso-postgres
    restart: always
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sso:
    build: .
    container_name: sso-service
    restart: always
    ports:
      - '4403:4404'
    depends_on:
      - postgres

volumes:
  postgres_data: {}