env: "local" # local, dev, prod
token_ttl: 1h
server:
  port: 4404
  timeout: 5s
database:
  host: "sso-postgres"
  port: 5432
  user: "sleeps"
  password: "$$Sleeps19122004"
  database: "sso"
  timeout: 10s
